blog/urls.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views import IndexView,PostDetailView,ArchivesView,CategoryView,TagsView,post_pub



app_name='blog'

urlpatterns=[
    url('^$',IndexView.as_view(),name='index'),
    url('^post/(?P<pk>\d+)/$',PostDetailView.as_view(),name='detail'),
    url('^archives/(?P<year>\d{4})/(?P<month>\d{1,2})/$',ArchivesView.as_view(),name='archives'),
    url('^category/(?P<pk>\d+)/$',CategoryView.as_view(),name='category'),
    url('^tags/(?P<pk>\d+)/$',TagsView.as_view(),name='tags'),
    url('^pubpost/(?P<user_pk>\d+)/$',post_pub,name='pubpost'),

]

myblog/urls.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-
"""myblog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from blog.feeds import AllPostRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/',include('users.urls')),
    url(r'',include('blog.urls')),
    url(r'^users/',include('django.contrib.auth.urls')),
    url(r'',include('comments.urls')),
    url(r'^all/rss/$',AllPostRssFeed(),name='rss'),
    url(r'^search/',include('haystack.urls')),
    url(r'^photo/',include('photo.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

photo/urls.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import pubphoto,ShowPhotoView,likes

app_name='photo'

urlpatterns=[
    url(r'^pub/(?P<user_pk>\d+)/$',pubphoto,name='pub'),
    url(r'^show/$',ShowPhotoView.as_view(),name='show'),
    url(r'^show/likes/(?P<photo_pk>\d+)/$',likes,name='likes')
]

users/urls.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views import register

app_name='users'

urlpatterns=[
    url('^register/$',register,name='register'),
]

blog/models.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-
from django.db import models
# from django.contrib.auth.models import User
from django.utils.html import strip_tags

from myblog.settings import MEDIA_ROOT
from users.models import User
from django.urls import reverse
import markdown

# Create your models here.
# 分类
class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

# 标签
class Tag(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

# #定义上传文章图片的方法
# def postimg_upload(instance,filename):
#     return "/".join([MEDIA_ROOT, instance.tilte,filename])


# 文章
class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()

    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    # 摘要
    excerpt = models.CharField(max_length=200,blank=True)
    category = models.ForeignKey('Category')
    tags = models.ManyToManyField('Tag')

    # 作者
    author = models.ForeignKey(User)

    # 阅读量
    views = models.PositiveIntegerField(default=0)

   # 文章图片
   #  url_height = models.PositiveIntegerField(default=340)
   #  url_width = models.PositiveIntegerField(default=840)
    img = models.ImageField(upload_to='avatar/post/%Y/%m/%d/',default='post.jpg')

    # 定义默认的排序方法,以发布时间倒序排列
    class Meta:
        ordering=['-created_time']

    def __str__(self):
        return self.title

    # 获取文章post的绝对url
    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk':self.pk})

    # 获得文章阅读量的方法
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    # 获得自动文章摘要的方法
    def save(self,*args,**kwargs):
        if not self.excerpt:
            md=markdown.Markdown(
                extensions=[
                    'markdown.extensions.extra',
                    'markdown.extensions.codehilite',
                ]
            )
            self.excerpt=strip_tags(md.convert(self.body))[:66]

        super().save(*args,**kwargs)

photo/models.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-
from django.db import models
from users.models import User

# Create your models here.
class MyPhoto(models.Model):
    title=models.CharField(max_length=60,verbose_name='标题')
    upload_time=models.DateTimeField(auto_now_add=True,verbose_name='上传时间')
    description=models.CharField(max_length=300,verbose_name='描述')
    photo=models.ImageField(upload_to='avatar/myphoto/%Y/%m/%d/')
    photo_author=models.ForeignKey(User,verbose_name='作者')
    views=models.PositiveIntegerField(verbose_name='点赞量',default=0)

    def __str__(self):
        return self.title

photo/forms.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-

from django import forms
from .models import MyPhoto

class PubPhotoForm(forms.ModelForm):
    class Meta:
        model=MyPhoto
        fields=['title','description','photo']

photo/views.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-
from django.http import JsonResponse
from django.shortcuts import render,get_object_or_404,redirect
from users.models import User
from .forms import PubPhotoForm
from django.views.generic import ListView

from .models import MyPhoto

# Create your views here.

# 发布图片
def pubphoto(request,user_pk):
   user = get_object_or_404(User,pk=user_pk)
   if request.method=='POST':
       form =  PubPhotoForm(request.POST,request.FILES)

       if form.is_valid():
           photo=form.save(commit=False)
           photo.photo_author=user
           photo.save()

           return redirect('/photo/show/')

       else:
           context={
               'form':form
           }
           return render(request,'photo/photopub.html',context=context)

   else:
       form=PubPhotoForm()
       return render(request,'photo/photopub.html',locals())

# def showphoto(request):
#     return render(request,'photo/show.html')

# 展示图片
class ShowPhotoView(ListView):
    model = MyPhoto
    template_name = 'photo/show.html'
    context_object_name = 'photo_list'

# 点赞的方法
def likes(request,photo_pk):
    myphoto=get_object_or_404(MyPhoto,pk=photo_pk)

    if request.method=='POST':
        myphoto.views+=1
        likes_num=myphoto.views
        myphoto.save()
        msg={'likesnum':likes_num}
        return  JsonResponse(msg)
    else:
        return redirect('/index/')

templates/photo/photopub.html
{% extends 'blog/base.html' %}

{% block main %}
      <article class="post">
				<div>

                    <h3>发布美图</h3>
                    <label>当前用户：<span style="color: #0e84b5"><img src="{{ user.headshot.url }} " height="30" width="30"/>{{ user.username }}</span></label>


                  <form method="post" action="{% url 'photo:pub' user.pk %}" enctype="multipart/form-data">
                      {% csrf_token %}
                        <p><label>标题：</label>
                        {{ form.title }}{{ form.title.errors  }}</p>
                        <p><label>描述：</label>
                        {{ form.description }}{{ form.description.errors }}<br></p>
                        <label>图片：</label>
                        {{ form.photo }}{{ form.photo.errors }}<br>

                        <div align="center" style="margin-top: 40px;font-size: 20px"><button type="submit">发布</button></div>

                    </form>

                </div>

      </article>
{% endblock %}

templates/photo/show.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Tangx's blog </title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />

  <!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

        <link rel="stylesheet" href="{% static 'assets/css/main.css' %}"/>
        <link rel="stylesheet" href="{% static 'assets/highlights/github.css' %}">
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
	<!-- Salvattore -->
	<link rel="stylesheet" href="{% static 'css/salvattore.css' %}">
	<!-- Theme Style -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->
     <style>
            .mysection li{list-style: none}
            .mysection a{margin: 5px;font-size: 20px;}
            .mytag a{border: 1px solid;padding: 5px;}
            .mytag li{display: inline-block;margin-top: 10px}
            .commentform{padding: 20px 0px }
            .mycomment {padding: 20px 0px;margin-top: 30px;border-top:1px solid }
            .commentform button{margin-top: 20px;}
            .mycomment li{padding: 10px 0px}
            .commentlist{padding: 20px 0px;margin-top: 30px;border-top:1px solid}
            .comment_created_time{margin-left: 100px}
            .comment_userinfo {display:inline-block;width: 200px}
            .comment-header {margin-bottom: 20px}
            span.highlighted { color: red; }
             #id_category{width: 200px}
             #id_tags {height: 100px;width: 200px}
             #mylogin{width: 30px;height: 56px}
            .likeadd{  visibility: hidden;color: red;font-style: italic}

        </style>
     <script>
            // 登录框
           window.onload=function (ev) {
                var oMylogin=document.getElementById('mylogin')
                var oMyloginul=document.getElementById('myloginul')
                var oMylogina=document.getElementById('mylogina')

                oMyloginul.onmouseover=function (ev2) {
                       oMyloginul.style.display='block'
                        oMylogina.style.backgroundColor='cadetblue'
                }
                oMylogin.onmouseover=function (ev2) {
                    oMyloginul.style.display='block'

                }

                 oMylogin.onmouseout=function (ev2) {
                    oMyloginul.style.display='none'
                    oMylogina.style.backgroundColor='#F8F8F8'
                }

            }
            //  点赞
             function likes(ths,photo_pk) {
             $.ajax({
                        type:'post',
                        url:"likes/"+photo_pk+'/',
                        dataType:'json',
                        data:{csrfmiddlewaretoken:'{{ csrf_token }}'},
                        success:function (data) {
                            ths.nextSibling.style.visibility='visible'

                            setTimeout(function(){ths.nextSibling.style.visibility='hidden'},

                                2000)

                           ths.nextSibling.nextSibling.innerHTML='&nbsp;&nbsp;&nbsp;&nbsp;'+data['likesnum']
                            console.log(ths.nextSibling.nextSibling.innerHTML)
                        }
                    })

            }

        </script>

	</head>
	<body>
		

    
    <div id="wrapper" >
        <!-- Header -->
					<header id="header">
						<h5 style="line-height: 52px;margin-top: -5px"><a href="{% url 'blog:index' %}">Tangx Blog</a></h5>
						<nav class="links">
							<ul>
								<li><a href="#">技术</a></li>
								<li><a href="{% url 'photo:show' %}">摄影</a></li>
								<li><a href="#">生活</a></li>
								<li><a href="#">感悟</a></li>
								<li><a href="#">About Me</a></li>
							</ul>
						</nav>

                        <nav class="links usernav">
                           <ul>
                               {% if user.is_authenticated  %}

                                <li class="cl-effect-11"><a href="#"><img src="{{ user.headshot.url }} " height="30" width="30"/></a></li>
                                <li class="cl-effect-11"><a href="#" data-hover="{{ user.username }}">{{ user.username }}</a></li>
                                <li class="cl-effect-11"><a href="{% url 'logout' %}?next={{ request.path }}" data-hover="注销">注销</a></li>
                                <li class="cl-effect-11"><a href="{% url 'password_change' %}?next={{ request.path }}" data-hover="修改密码">修改密码</a></li>
                                 <li class="cl-effect-11"><a href="{% url 'photo:pub' user.pk %}" data-hover="发布">秀一下美图</a></li>
                            {% else %}
                                <li class="cl-effect-11" id="mylogin" >
{#                                    <a href="{% url 'login' %}?next={{ request.path }}" data-hover="登录">登录</a>#}
                                    <a id='mylogina' style="cursor: pointer" >登录</a>

                                    <ul  id="myloginul" style="display: none;background-color:white;position: absolute;padding: 20px;margin-top:18px;margin-left: -25px;border: 1px solid #dcdccc">
                                        <form style="width: 300px" method="post" action="{% url 'login' %}?next={{ request.path }}">
                                            {% csrf_token %}
                                            <input style="padding: 10px;margin-top: 10px" name = username type="text" placeholder="用户名">
                                            <input style="padding: 10px;margin-top: 10px" name=password type="password" placeholder="密码">
                                            <input style="padding: 10px;margin-top: 10px;font-size:16px;line-height: 20px" type="submit" value="登录">
                                        </form>
                                    </ul>

                                </li>
                                <li class="cl-effect-11"><a href="{% url 'users:register' %}?next={{ request.path }}" data-hover="注册">注册</a></li>
                            {% endif %}

                           </ul>

						</nav>

						<nav class="main">
							<ul>
								<li class="search">
									<a class="fa-search" href="#search">Search</a>
									<form id="search" method="get" action="{% url 'haystack_search' %}">
										<input type="text" name="q" placeholder="Search" />
									</form>
								</li>
								<li class="menu">
									<a class="fa-bars" href="#menu">Menu</a>
								</li>
							</ul>
						</nav>
					</header>

				<!-- Menu -->
					<section id="menu">

						<!-- Search -->
							<section>
								<form class="search" method="get" action="{% url 'haystack_search' %}">
									<input type="text" name="q" placeholder="Search" />
								</form>
							</section>

						<!-- Links -->
							<section>
								<ul class="links">
									<li>
										<a href="#">
											<h3>技术</h3>
											<p>技术进化的道路上，没有尽头</p>
										</a>
									</li>
									<li>
										<a href="#">
											<h3>摄影</h3>
											<p>拍到好照片，纯属运气</p>
										</a>
									</li>
									<li>
										<a href="#">
											<h3>生活</h3>
											<p>生活无非是给自己找乐子</p>
										</a>
									</li>
									<li>
										<a href="#">
											<h3>about me</h3>
											<p>虎起来，都不知道自己是谁</p>
										</a>
									</li>
								</ul>
							</section>

						<!-- Actions -->
							<section>
								<ul class="actions vertical">
									<li><a href="{% url 'login' %}?next={{ request.path }}" class="button big fit">登录</a></li>
								</ul>
							</section>

					</section>

    </div>
	
	
	<div id="fh5co-main" style="margin-top: -60px">
		<div class="container">

			<div class="row">

        <div id="fh5co-board" data-columns>

            {% for photo in photo_list %}
                <div class="item">
                        <div class="animate-box">
                            <a href="{{ photo.photo.url }}" class="image-popup fh5co-board-img" title="{{ photo.title }}"><img src="{{ photo.photo.url }}" alt="{{ photo.photo_author }}"></a>
                        </div>
        		<div class="fh5co-desc">
                    <h5>{{ photo.title }}</h5>
                    <span>{{ photo.description }}</span><br>
                    <span>{{ photo.upload_time }}</span><br>
                    <div><a class="icon fa-heart like" style="color:palevioletred;cursor: pointer;display: inline" onclick="likes(this,{{ photo.pk }});"></a><span class="likeadd">点赞+1</span><span>&nbsp;&nbsp;&nbsp;&nbsp;{{ photo.views }}</span></div>
                    <span style="margin-left:150px ">
                        <img src="{{ photo.photo_author.headshot.url }}" style="width: 25px;height: 25px">{{ photo.photo_author }}
                    </span>
                </div>
        	</div>

            {% endfor %}






        </div>
        </div>
       </div>
	</div>


	<!-- jQuery -->
	<script src="http://www.jq22.com/jquery/jquery-1.10.2.js"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="http://www.jq22.com/jquery/bootstrap-3.3.4.js"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Magnific Popup -->
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<!-- Salvattore -->
	<script src="{% static 'js/salvattore.min.js' %}"></script>
	<!-- Main JS -->
	<script src="{% static 'js/main.js' %}"></script>

{#    <!-- Scripts -->#}
{#			<script src="{% static 'assets/js/jquery.min.js' %}"></script>#}
{#			<script src="{% static 'assets/js/skel.min.js' %}"></script>#}
{#			<script src="{% static 'assets/js/util.js' %}"></script>#}
{#			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->#}
{#			<script src="{% static 'assets/js/main.js' %}"></script>#}


	

	
	</body>
</html>