blog/urls.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views import IndexView,PostDetailView,ArchivesView,CategoryView,TagsView,post_pub



app_name='blog'

urlpatterns=[
    url('^$',IndexView.as_view(),name='index'),
    url('^post/(?P<pk>\d+)/$',PostDetailView.as_view(),name='detail'),
    url('^archives/(?P<year>\d{4})/(?P<month>\d{1,2})/$',ArchivesView.as_view(),name='archives'),
    url('^category/(?P<pk>\d+)/$',CategoryView.as_view(),name='category'),
    url('^tags/(?P<pk>\d+)/$',TagsView.as_view(),name='tags'),
    url('^pubpost/(?P<user_pk>\d+)/$',post_pub,name='pubpost'),

]

myblog/urls.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-
"""myblog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from blog.feeds import AllPostRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/',include('users.urls')),
    url(r'',include('blog.urls')),
    url(r'^users/',include('django.contrib.auth.urls')),
    url(r'',include('comments.urls')),
    url(r'^all/rss/$',AllPostRssFeed(),name='rss'),
    url(r'^search/',include('haystack.urls')),
    url(r'^photo/',include('photo.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

comments/models.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-
from django.db import models
from users.models import User
from blog.models import Post

# Create your models here.
# 评论模型
class Comment(models.Model):
    text=models.TextField()
    created_time=models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User)
    post=models.ForeignKey(Post)

    def __str__(self):
        return self.text[:20]

templates/search/search.html
{% extends 'blog/base.html' %}
{% load highlight %}


{% block main %}

            {% if query %}
                    {% for result in page.object_list %}
                            <article class="post">
								<header>
									<div class="title">
										<h2><a href="{{ result.object.get_absolute_url }}">{% highlight result.object.title with query %}</a></h2>
										<p>{{ result.object.excerpt }}</p>
									</div>
									<div class="meta">
										<time class="published" datetime="2015-10-22">{{ result.object.created_time }}</time>
										<a href="#" class="author"><span class="name">{{ result.object.author }}</span><img src="{{ result.object.author.headshot.url }}" alt="" /></a>
									</div>
								</header>
								<a href="#" class="image featured"><img src="{{ result.object.img.url }}" alt="" /></a>
								<p> {% highlight result.object.body with query | truncatechars:210 %}</p>
								<footer>
									<ul class="actions">
										<li><a href="{{ result.object.get_absolute_url }}" class="button big">继续阅读</a></li>
									</ul>
									<ul class="stats">
										<li><a href="{% url 'blog:category' result.object.category.pk %}">{{ result.object.category }}</a></li>
										<li><a href="{{ result.object.get_absolute_url }}" class="icon fa-heart">{{ result.object.views }}</a></li>
										<li><a href="{{ result.object.get_absolute_url }}" class="icon fa-comment">{{ presult.object.comment_set.all.count }}</a></li>
									</ul>
								</footer>
							</article>

                        {% empty %}
                            没有搜索到你想要的结果！
                        {% endfor %}
                        <!-- Pagination -->
                        {% if is_paginated %}
                              <ul class="actions pagination">
                                {% if page_obj.has_previous %}
								      <li><a href="?page={{ page_obj.previous_page_number }}" class=" button big previous">上一页</a></li>
                                {% endif %}

                                 {% if page_obj.has_next %}
                                     <li><a href="?page={{ page_obj.next_page_number }}" class="button big next">下一页</a></li>
                                 {% endif %}

							  </ul>
                        {% endif %}
{#                        	<ul class="actions pagination">#}
{#								<li><a href="" class="disabled button big previous">Previous Page</a></li>#}
{#								<li><a href="#" class="button big next">Next Page</a></li>#}
{#							</ul>#}
            {% else %}
                   请输入搜索关键词，例如 bootstrap
            {% endif %}

{% endblock %}