blog/urls.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views import IndexView,PostDetailView,ArchivesView,CategoryView,TagsView,post_pub



app_name='blog'

urlpatterns=[
    url('^$',IndexView.as_view(),name='index'),
    url('^post/(?P<pk>\d+)/$',PostDetailView.as_view(),name='detail'),
    url('^archives/(?P<year>\d{4})/(?P<month>\d{1,2})/$',ArchivesView.as_view(),name='archives'),
    url('^category/(?P<pk>\d+)/$',CategoryView.as_view(),name='category'),
    url('^tags/(?P<pk>\d+)/$',TagsView.as_view(),name='tags'),
    url('^pubpost/(?P<user_pk>\d+)/$',post_pub,name='pubpost'),

]

comments/urls.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from .views import post_comment

app_name='comments'
urlpatterns=[
    url(r'^comments/post/(?P<post_pk>\d+)/(?P<user_pk>\d+)/$',post_comment,name='post_comment'),
]

myblog/urls.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-
"""myblog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from blog.feeds import AllPostRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/',include('users.urls')),
    url(r'',include('blog.urls')),
    url(r'^users/',include('django.contrib.auth.urls')),
    url(r'',include('comments.urls')),
    url(r'^all/rss/$',AllPostRssFeed(),name='rss'),
    url(r'^search/',include('haystack.urls')),
    url(r'^photo/',include('photo.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-
from django.db import models
# from django.contrib.auth.models import User
from django.utils.html import strip_tags

from myblog.settings import MEDIA_ROOT
from users.models import User
from django.urls import reverse
import markdown

# Create your models here.
# 分类
class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

# 标签
class Tag(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

# #定义上传文章图片的方法
# def postimg_upload(instance,filename):
#     return "/".join([MEDIA_ROOT, instance.tilte,filename])


# 文章
class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()

    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    # 摘要
    excerpt = models.CharField(max_length=200,blank=True)
    category = models.ForeignKey('Category')
    tags = models.ManyToManyField('Tag')

    # 作者
    author = models.ForeignKey(User)

    # 阅读量
    views = models.PositiveIntegerField(default=0)

   # 文章图片
   #  url_height = models.PositiveIntegerField(default=340)
   #  url_width = models.PositiveIntegerField(default=840)
    img = models.ImageField(upload_to='avatar/post/%Y/%m/%d/',default='post.jpg')

    # 定义默认的排序方法,以发布时间倒序排列
    class Meta:
        ordering=['-created_time']

    def __str__(self):
        return self.title

    # 获取文章post的绝对url
    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk':self.pk})

    # 获得文章阅读量的方法
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    # 获得自动文章摘要的方法
    def save(self,*args,**kwargs):
        if not self.excerpt:
            md=markdown.Markdown(
                extensions=[
                    'markdown.extensions.extra',
                    'markdown.extensions.codehilite',
                ]
            )
            self.excerpt=strip_tags(md.convert(self.body))[:66]

        super().save(*args,**kwargs)

comments/models.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-
from django.db import models
from users.models import User
from blog.models import Post

# Create your models here.
# 评论模型
class Comment(models.Model):
    text=models.TextField()
    created_time=models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User)
    post=models.ForeignKey(Post)

    def __str__(self):
        return self.text[:20]

blog/forms.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-

from django import forms
from .models import Post

# 定义发布文章的表单类
class PubForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','body','excerpt','category','tags','img',]

blog/views.py
#!/home/blogenv/bin/python
# -*- coding: utf-8 -*-
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import ListView,DetailView
from .forms import PubForm
from .models import Post,Category,Tag
from users.models import User
import markdown
from comments.forms import CommentForm



# Create your views here.

# 首页
# def index(request):
#     post_list = Post.objects.all().order_by('-created_time')
#     return render(request,'blog/index.html',{'post_list':post_list})

# 首页视图类
class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    # 每页显示三篇文章
    paginate_by = 3



# 博客详情页
def detail(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post.increase_views()
    post.body = markdown.markdown(post.body,extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    form = CommentForm()
    comment_list = post.comment_set.all()

    return render (request, 'blog/detail.html', locals())

# 博客详情页视图类
class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    # 复写 get方法，每次执行视图执行增加阅读量功能
    def get(self, request, *args, **kwargs):
        # 先调用父类的get方法，self.object属性中才会有Post模型的实例
        response = super().get(request, *args, **kwargs)
        # self.object的值就是被访问的文章对象post
        self.object.increase_views()
        # 返回response
        return response

    # 复写get_object,post的body值进行渲染为markdown
    def get_object(self, queryset=None):
        post = super().get_object(queryset=None)
        post.body = markdown.markdown(post.body,extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
        ])

        return post

    # 复写get_context_data方法，拓展response中context的内容
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
         'form':form,
         'comment_list':comment_list
        })
        return context





# 归档视图
# def archives(request,year,month):
#     post_list = Post.objects.filter(created_time__year=year,
#                                   created_time__month=month).order_by('-created_time')
#     return render(request,'blog/index.html',locals())


# 归档视图类
class ArchivesView(IndexView):
    def get_queryset(self):
        year=self.kwargs.get('year')
        month=self.kwargs.get('month')
        return super().get_queryset().filter(created_time__year=year,created_time__month=month)

# 分类视图
# def category(request,pk):
#     cate=get_object_or_404(Category,pk=pk)
#     post_list=Post.objects.filter(category=cate).order_by('-created_time')
#     return render(request,'blog/index.html',locals())

# 分类视图类


class CategoryView (IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super().get_queryset().filter(category=cate)


# 标签云视图类
class TagsView(IndexView):
    def get_queryset(self):
        tag = get_object_or_404(Tag,pk=self.kwargs.get('pk'))
        return super().get_queryset().filter(tags=tag)



# 发布文章的视图函数
def post_pub(request,user_pk):
    # 获得登录的用户对象

    user=get_object_or_404(User,pk=user_pk)
    # 如果为post方法
    if request.method=='POST':
        form=PubForm(request.POST,request.FILES)
        # 如果表单内容合规
        if form.is_valid():
            # 创建文章对象，不保存到数据库
            post=form.save(commit=False)


            post.author=user

            # 保存文章表单数据到数据库,重定向当前页
            post.save()
            return redirect('/index/')
        else:

            # 将当前页面表单内容，文章，评论列表保存后，重新渲染页面
            context={

                'form':form,

            }
            return render(request,'blog/pub.html',context=context)
    else:
        # get访问时，刷新页面
        form = PubForm()
        return render(request,'blog/pub.html',locals())

templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block main %}
      <article class="post">
								<header>
									<div class="title">
										<h2><a href="#">{{ post.title }}</a></h2>
										<p>{{ post.excerpt }}</p>
									</div>
									<div class="meta">
										<time class="published" datetime="{{ post.created_time }}">{{ post.created_time }}</time>
										<a href="#" class="author"><span class="name">{{ post.author }}</span><img src="{{ post.author.headshot.url }}" alt="" /></a>
									</div>
								</header>
								<a href="#" class="image featured"><img src="{{ post.img.url }}" alt="" /></a>
								<p>{{ post.body|safe }}</p>

                                <footer>
									<ul class="stats">
										<li><a href="{% url 'blog:category' post.category.pk %}">{{ post.category }}</a></li>
										<li><a href="{{ post.get_absolute_url }}" class="icon fa-heart">{{ post.views }}</a></li>
										<li><a href="{{ post.get_absolute_url }}#comment-area" class="icon fa-comment">{{ post.comment_set.all.count }}</a></li>
									</ul>

								</footer>
                                <footer>
                                     <ul class="stats">
                                        <span style="font-size: 14px">标签：</span>
                                        {% for tag in post.tags.all %}
                                            <li ><a href="{% url 'blog:tags' tag.pk %}" style="padding:0px 3px;border-radius: 3px;border: 1px solid;background-color: #8fbede">{{ tag.name }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </footer>

                                <div class="commentlist  " id="#comment-area">
                                        <h4>当前评论：</h4>
                                         <ul>
                                             {% for comment in comment_list %}
                                                 <li style="list-style: none;border-top: 1px dotted">
                                                    <div class="comment-header" style="padding: 10px"><span class="comment_userinfo" ><img src="{{ comment.user.headshot.url }} " height="30" width="30"/>
                                                    {{ comment.user.nickname }}</span><span class="comment_created_time" >{{ comment.created_time }}</span></div>
                                                    <p >{{ comment.text }}</p>

                                                 </li>
                                             {% empty %}
                                                 暂无评论
                                             {% endfor %}


                                         </ul>
                                </div>

                                {% if user.is_authenticated  %}
                                     <div class="mycomment">


                                         <li style="list-style: none">
                                             <a href="#"><img src="{{ user.headshot.url }} " height="30" width="30"/></a>
                                             <a href="#" data-hover="{{ user.username }}" style="font-size: 20px">{{ user.username }}</a>
                                         </li>

                                        <li style="list-style: none"><a href="#">{{ user.signature}}</a></li>

                                        <form action="{% url 'comments:post_comment' post.pk user.pk%}" method="post">
                                            {% csrf_token %}
                                            <div class="commentform">
                                                <label for="{{ form.text.id_for_label }}"><h5>评论：</h5></label>
                                                {{ form.text }}
                                                {{ form.text.errors }}
                                                <button type="submit" >发表</button>

                                            </div>

                                        </form>




                                     </div>

                                {% else %}
                                   <h4>请 <a href="{% url 'login' %}?next={{ request.path }}" style="color:rebeccapurple">登录</a>后进行评论！</h4>

                                {% endif %}

							</article>
{% endblock %}

templates/blog/index.html
{% extends 'blog/base.html' %}

{% block main %}
                        {% for post in post_list %}
                            <article class="post">
								<header>
									<div class="title">
										<h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
										<p>{{ post.excerpt }}</p>
									</div>
									<div class="meta">
										<time class="published" datetime="2015-10-22">{{ post.created_time }}</time>
										<a href="#" class="author"><span class="name">{{ post.author }}</span><img src="{{ post.author.headshot.url }}" alt="" /></a>
									</div>
								</header>
								<a href="#" class="image featured"><img src="{{ post.img.url }}" alt="" /></a>
								<p>{{ post.body | truncatechars:210 }}</p>
								<footer>
									<ul class="actions">
										<li><a href="{{ post.get_absolute_url }}" class="button big">继续阅读</a></li>
									</ul>
									<ul class="stats">
										<li><a href="{% url 'blog:category' post.category.pk %}">{{ post.category }}</a></li>
										<li><a href="{{ post.get_absolute_url }}" class="icon fa-heart">{{ post.views }}</a></li>
										<li><a href="{{ post.get_absolute_url }}" class="icon fa-comment">{{ post.comment_set.all.count }}</a></li>
									</ul>
								</footer>
							</article>

                        {% empty %}
                            暂无文章收录
                        {% endfor %}
                        <!-- Pagination -->
                        {% if is_paginated %}
                              <ul class="actions pagination">
                                {% if page_obj.has_previous %}
								      <li><a href="?page={{ page_obj.previous_page_number }}" class=" button big previous">上一页</a></li>
                                {% endif %}

                                 {% if page_obj.has_next %}
                                     <li><a href="?page={{ page_obj.next_page_number }}" class="button big next">下一页</a></li>
                                 {% endif %}

							  </ul>
                        {% endif %}
{#                        	<ul class="actions pagination">#}
{#								<li><a href="" class="disabled button big previous">Previous Page</a></li>#}
{#								<li><a href="#" class="button big next">Next Page</a></li>#}
{#							</ul>#}

{% endblock %}

templates/blog/pub.html
{% extends 'blog/base.html' %}

{% block main %}
      <article class="post">
				<div>

                    <h3>发布文章</h3>
                    <label>当前用户：<span style="color: #0e84b5"><img src="{{ user.headshot.url }} " height="30" width="30"/>{{ user.username }}</span></label>


                  <form method="post" action="{% url 'blog:pubpost' user.pk %}" enctype="multipart/form-data">
                      {% csrf_token %}
                     <p><label>标题：</label>
                        {{ form.title }}{{ form.title.errors  }}</p>
                        <p><label>内容：</label>
                        {{ form.body }}{{ form.body.errors }}<br></p>
                        <label>摘要：</label>
                        {{ form.excerpt }}{{ form.excerpt.errors }}<br>
                        <label>分类：</label>
                          {{ form.category }}{{ form.category.errors }}<br>
                        <label>标签：</label>
                        {{ form.tags }}{{ form.tags.errors }}
                        <br>
                        <label>图片：</label>
                        {{ form.img }}{{ form.img.errors }}<br>

                        <div align="center" style="margin-top: 40px;font-size: 20px"><button type="submit">发布</button></div>

                    </form>

                </div>

      </article>
{% endblock %}